Repository BE-UPP/be-upp-backend, pull requests merged in 2021-12, with the labels that each got.

#44 Alterações nos campos do doutor
  src/data/models/doctor.js
  src/route/openApis/doctor.js
  src/service/doctor.js
  src/test/doctor.test.js
Labels: Sprint-5, Backend

#49 Erro cadastro consulta
  package.json
  src/test/appointment.test.js
  src/test/seed.js
Labels: Sprint-5, Backend

#57 Restringir acesso apis
  .circleci/config.yml
  .env-example
  .gitignore
  package-lock.json
  package.json
  prod/dockerfiles/Dockerfile-app
  requests.rest
  src/doc/swagger.js
  src/route/closeApis.js
  src/route/closeApis/appointment.js
  src/route/closeApis/doctor.js
  src/route/openApis.js
  src/route/openApis/doctor.js
  src/server.js
  src/service/authentication.js
  src/service/doctor.js
  src/test/appointment.test.js
  src/test/doctor.test.js
Labels: Sprint-4, Sprint-5, Backend

#42 Ajustar modelos para processamento
  package.json
  src/data/models/data-processing.js
  src/data/models/form-data.js
  src/service/data-processing.js
  src/service/form-data.js
  src/service/helper.js
  src/service/template.js
  src/test/appointment.test.js
  src/test/data-processing.test.js
  src/test/form-data.test.js
  src/test/template.test.js
Labels: Sprint-5, Backend

#52 Api get id appointment
  src/route/closeApis/appointment.js
  src/test/appointment.test.js
Labels: Sprint-5, Backend

#54 Configurado envio de email para paciente
  src/service/appointment.js
Labels: Sprint-5, Backend

#62 Telefone do consultório opcional
  src/route/openApis/doctor.js
  src/service/doctor.js
Labels: Backend

#63 Modelo e serviços do Relatório Final criados
  src/data/models/final-report.js
  src/data/models/form-data.js
  src/service/final-report.js
  src/service/form-data.js
  src/service/helper.js
  src/test/final-report.test.js
Labels: Sprint-5, Backend

#64 Resolvendo warnings do tipo "Expected an object to be thrown no-throw-literal"
  src/route/closeApis/appointment.js
  src/route/closeApis/doctor.js
  src/route/closeApis/patient.js
  src/route/openApis/doctor.js
  src/route/openApis/template.js
  src/service/appointment.js
Labels: BUG, Backend

#66 Criar modelo relatorio
  src/data/models/final-report.js
  src/data/models/form-data.js
  src/route/openApis/data-processing.js
  src/service/final-report.js
  src/service/form-data.js
  src/service/helper.js
  src/test/final-report.test.js
Labels: Sprint-5, Backend

#68 Alterando código de erro em /src/route/closeApis/appointment.js
  src/route/closeApis/appointment.js
Labels: BUG, Backend

#67 Refatorado formdata e processdata
  src/data/models/final-report.js
  src/route/openApis/form-data.js
  src/service/data-processing.js
  src/service/template.js
  src/test/data-processing.test.js
  src/test/form-data.test.js
  src/test/template.test.js
Labels: Sprint-5, Backend

#71 APIs do relatório final e do formData finalizadas
  src/route/closeApis.js
  src/route/closeApis/final-report.js
  src/route/openApis/form-data.js
  src/service/data-processing.js
  src/service/final-report.js
  src/service/helper.js
  src/test/data-processing.test.js
  src/test/final-report.test.js
  src/test/form-data.test.js
  src/test/seed.js
Labels: Sprint-5, Backend

#74 Novos tipos de DataProcessing + ajustes
  src/data/models/data-processing.js
  src/route/closeApis/final-report.js
  src/route/openApis.js
  src/route/openApis/data-processing.js
  src/route/openApis/doctor.js
  src/route/openApis/final-report.js
  src/route/openApis/form-data.js
  src/service/data-processing.js
  src/service/final-report.js
  src/test/data-processing.test.js
  src/test/final-report.test.js
Labels: Backend, Sprint-6

#75 Nova release
  src/data/models/data-processing.js
  src/route/closeApis/final-report.js
  src/route/openApis.js
  src/route/openApis/data-processing.js
  src/route/openApis/doctor.js
  src/route/openApis/final-report.js
  src/route/openApis/form-data.js
  src/service/data-processing.js
  src/service/final-report.js
  src/test/data-processing.test.js
  src/test/final-report.test.js
Labels: Backend, Sprint-6

#77 Adicionado casos especiais em DataProcessing
  src/service/data-processing.js
  src/test/data-processing.test.js
Labels: BUG, Backend, Sprint-6

#81 Adicionado restrição de paciente a doutor
  src/data/models/patient.js
  src/route/closeApis/patient.js
  src/service/patient.js
  src/test/patient.test.js
Labels: Backend, Sprint-6
