Repository BE-UPP/be-upp-backend, pull requests merged in 2021-11, with the labels that each got.

#26 Criada api de listar todos os pacientes
  src/route/openApis/patient.js
  src/service/patient.js
  src/test/patient.test.js
Labels: Sprint-4, Backend

#28 Criada API login doutor
  src/route/openApis/doctor.js
  src/service/doctor.js
  src/test/doctor.test.js
Labels: Sprint-3, Backend

#33 Alterados novos campos do doutor e retirado envio da senha nas APIs
  src/data/models/doctor.js
  src/route/openApis/doctor.js
  src/service/doctor.js
  src/service/helper.js
  src/test/appointment.test.js
  src/test/doctor.test.js
  src/test/form-data.test.js
Labels: Sprint-4, Backend

#32 Retirar senha da API de listar pacientes
  src/service/patient.js
  src/test/patient.test.js
Labels: Sprint-4, BUG, Backend

#35 Implementação do modelo e do serviço de processamento de dados
  package-lock.json
  package.json
  src/data/models/data-processing.js
  src/data/models/form-data.js
  src/route/openApis/form-data.js
  src/service/data-processing.js
  src/test/data-processing.test.js
Labels: Sprint-4, Backend
